FROM node:alpine3.19

ENV NODE_TLS_REJECT_UNAUTHORIZED=$NODE_TLS_REJECT_UNAUTHORIZED
ENV NIMBUS_API_HOST=$NIMBUS_API_HOST
ENV NEXT_PUBLIC_NIMBUS_API_HOST=$NEXT_PUBLIC_NIMBUS_API_HOST

EXPOSE 4000:4000

COPY ./ /var/nimbus-frontend/
WORKDIR /var/nimbus-frontend/

RUN npm install
RUN npm run fe:build

CMD [ "npm", "run", "fe:start" ]