import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { PathContext, ProfileContext, Providers } from './layout-page';
import React from 'react';
import Link from 'next/link';

// import "./globals.css";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <Providers>
            <html lang="en">
                <body className={inter.className}>
                    <div
                        style={{
                            display: 'flex',
                            flexDirection: 'row',
                            gap: '20px',
                        }}
                    >
                        <Link href={'/login'}>Login</Link>
                        <Link href={'/register'}>Register</Link>
                        <Link href={'/files/my'}>My files</Link>
                        <Link href={'/files/trash'}>Trash files</Link>
                        <Link href={'/files/shared'}>Shared files</Link>
                    </div>
                    {children}
                </body>
            </html>
        </Providers>
    );
}
