version: 0.0
os: linux
files:
  - source: /
    destination: /var/nimbus-app/
hooks:
  ApplicationStop:
    - location: deploy-scripts/ApplicationStop.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy-scripts/ApplicationStart.sh
      timeout: 300
      runas: root
