version: 0.0
os: linux
files:
  - source: /
    destination: /var/nimbus-app/
hooks:
  BeforeInstall:
    - location: scripts/before-install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy-scripts/after-install.sh
      timeout: 300
      runas: ec2-user