version: "3.8"
services:
  db:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_gui_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_GUI_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_GUI_PASSWORD}
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
  
  mongo:
    image: mongo
    container_name: mongo_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASSWORD}

  mongo-express:
    image: mongo-express
    container_name: mongo_gui_container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo_container
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_GUI_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_GUI_PASSWORD}

volumes:
  pgadmin_vol:
  postgres_vol:
  