version: "3.8"
services:
  caddy_reverse_proxy:
    image: caddy:alpine
    container_name: caddy_reverse_proxy_container
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./backend/caddy/deploy-staging.Caddyfile:/etc/caddy/Caddyfile
      - ./backend/caddy/static:/code/static
      - caddy_data:/data
      - caddy_config:/config

  nimbus-api:
    image: nimbus/api
    # image: 913580947034.dkr.ecr.eu-north-1.amazonaws.com/nimbus-image-registry:nimbus_api-latest
    container_name: nimbus-api
    ports:
      - "3000:3000"
    build:
      context: ./backend
      dockerfile: build_api.Dockerfile
      
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_vol:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres_gui_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    volumes:
      - pgadmin_vol:/var/lib/pgadmin
  
  mongo:
    image: nimbus/mongo
    container_name: mongo_container
    environment:
      MONGO_ADMIN_USERNAME: root
      MONGO_ADMIN_PASSWORD: root
      MONGO_GUI_USERNAME: ${MONGO_GUI_USERNAME}
      MONGO_GUI_PASSWORD: ${MONGO_GUI_PASSWORD}
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: dev_tree_db
    build:
      context: ./backend
      dockerfile: ./rs.Dockerfile
    restart: always 
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo_gui_container
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo_container
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_GUI_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_GUI_PASSWORD}

  nimbus-redis:
    image: redis:7.0.14
    container_name: nimbus_redis_container
    ports:
      - 6379:6379
    volumes:
      - redis_vol:/data
      
volumes:
  pgadmin_vol:
  postgres_vol:
  redis_vol:
  caddy_data:
  caddy_config: