import React from 'react';
import Providers from '@/app/providers';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <Providers>
            <html lang="en">
                <body>{children}</body>
            </html>
        </Providers>
    );
}
